//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENT()
        {
            this.DOWNLOAD = new HashSet<DOWNLOAD>();
        }
    
        public System.Guid Content_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public System.Guid Uploader_Id { get; set; }
        public int Content_Type_Id { get; set; }
        public decimal Cost { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.Guid> Approver_Id { get; set; }
        public string URL { get; set; }
        public string Size { get; set; }
    
        public virtual CONTENT_TYPE CONTENT_TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOWNLOAD> DOWNLOAD { get; set; }
    }
}
