//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOWNLOAD
    {
        public System.Guid Download_Id { get; set; }
        public System.Guid Content_Id { get; set; }
        public System.Guid Payment_Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CONTENT CONTENT { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
